// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobsByStatus = `-- name: CountJobsByStatus :one
SELECT 
    COUNT(*) FILTER (WHERE status = 'queued') AS queued,
    COUNT(*) FILTER (WHERE status = 'processing') AS processing,
    COUNT(*) FILTER (WHERE status = 'completed') AS completed,
    COUNT(*) FILTER (WHERE status = 'failed') AS failed,
    COUNT(*) AS total
FROM jobs
`

type CountJobsByStatusRow struct {
	Queued     int64 `json:"queued"`
	Processing int64 `json:"processing"`
	Completed  int64 `json:"completed"`
	Failed     int64 `json:"failed"`
	Total      int64 `json:"total"`
}

func (q *Queries) CountJobsByStatus(ctx context.Context) (CountJobsByStatusRow, error) {
	row := q.db.QueryRow(ctx, countJobsByStatus)
	var i CountJobsByStatusRow
	err := row.Scan(
		&i.Queued,
		&i.Processing,
		&i.Completed,
		&i.Failed,
		&i.Total,
	)
	return i, err
}

const getJob = `-- name: GetJob :one

SELECT id, input_key, status, error_message, retry_count, max_retries, started_at, worker_id, created_at, updated_at FROM jobs
WHERE id = $1
`

// GraphQL service queries (read-only)
func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.InputKey,
		&i.Status,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.MaxRetries,
		&i.StartedAt,
		&i.WorkerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRenditionsByJobID = `-- name: GetRenditionsByJobID :many
SELECT id, job_id, resolution, output_key, created_at FROM renditions
WHERE job_id = $1
ORDER BY resolution
`

func (q *Queries) GetRenditionsByJobID(ctx context.Context, jobID pgtype.UUID) ([]Rendition, error) {
	rows, err := q.db.Query(ctx, getRenditionsByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rendition{}
	for rows.Next() {
		var i Rendition
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Resolution,
			&i.OutputKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, input_key, status, error_message, retry_count, max_retries, started_at, worker_id, created_at, updated_at FROM jobs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.InputKey,
			&i.Status,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.MaxRetries,
			&i.StartedAt,
			&i.WorkerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT id, input_key, status, error_message, retry_count, max_retries, started_at, worker_id, created_at, updated_at FROM jobs
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsByStatusParams struct {
	Status JobStatus `json:"status"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.InputKey,
			&i.Status,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.MaxRetries,
			&i.StartedAt,
			&i.WorkerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
