// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

// Represents a transcoding job
type Job struct {
	ID           string       `json:"id"`
	Status       JobStatus    `json:"status"`
	InputKey     string       `json:"inputKey"`
	ErrorMessage *string      `json:"errorMessage,omitempty"`
	CreatedAt    time.Time    `json:"createdAt"`
	UpdatedAt    time.Time    `json:"updatedAt"`
	Renditions   []*Rendition `json:"renditions"`
}

type Query struct {
}

// Represents a single rendition (output format) of a job
type Rendition struct {
	ID         string  `json:"id"`
	Resolution string  `json:"resolution"`
	OutputKey  *string `json:"outputKey,omitempty"`
}

// System-wide metrics for monitoring
type SystemMetrics struct {
	QueueDepth     int `json:"queueDepth"`
	TotalJobs      int `json:"totalJobs"`
	CompletedJobs  int `json:"completedJobs"`
	FailedJobs     int `json:"failedJobs"`
	ProcessingJobs int `json:"processingJobs"`
}

// Status of a transcoding job
type JobStatus string

const (
	JobStatusPending    JobStatus = "pending"
	JobStatusProcessing JobStatus = "processing"
	JobStatusCompleted  JobStatus = "completed"
	JobStatusFailed     JobStatus = "failed"
)

var AllJobStatus = []JobStatus{
	JobStatusPending,
	JobStatusProcessing,
	JobStatusCompleted,
	JobStatusFailed,
}

func (e JobStatus) IsValid() bool {
	switch e {
	case JobStatusPending, JobStatusProcessing, JobStatusCompleted, JobStatusFailed:
		return true
	}
	return false
}

func (e JobStatus) String() string {
	return string(e)
}

func (e *JobStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobStatus", str)
	}
	return nil
}

func (e JobStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
