// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (input_key, status)
VALUES ($1, 'queued')
RETURNING id, input_key, status, error_message, created_at, updated_at
`

func (q *Queries) CreateJob(ctx context.Context, inputKey string) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, inputKey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.InputKey,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRendition = `-- name: CreateRendition :one
INSERT INTO renditions (job_id, resolution)
VALUES ($1, $2)
RETURNING id, job_id, resolution, output_key, created_at
`

type CreateRenditionParams struct {
	JobID      pgtype.UUID `json:"job_id"`
	Resolution string      `json:"resolution"`
}

func (q *Queries) CreateRendition(ctx context.Context, arg CreateRenditionParams) (Rendition, error) {
	row := q.db.QueryRow(ctx, createRendition, arg.JobID, arg.Resolution)
	var i Rendition
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Resolution,
		&i.OutputKey,
		&i.CreatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, input_key, status, error_message, created_at, updated_at FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.InputKey,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRendition = `-- name: GetRendition :one
SELECT id, job_id, resolution, output_key, created_at FROM renditions
WHERE id = $1
`

func (q *Queries) GetRendition(ctx context.Context, id pgtype.UUID) (Rendition, error) {
	row := q.db.QueryRow(ctx, getRendition, id)
	var i Rendition
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Resolution,
		&i.OutputKey,
		&i.CreatedAt,
	)
	return i, err
}

const getRenditionsByJobID = `-- name: GetRenditionsByJobID :many
SELECT id, job_id, resolution, output_key, created_at FROM renditions
WHERE job_id = $1
ORDER BY resolution
`

func (q *Queries) GetRenditionsByJobID(ctx context.Context, jobID pgtype.UUID) ([]Rendition, error) {
	rows, err := q.db.Query(ctx, getRenditionsByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rendition{}
	for rows.Next() {
		var i Rendition
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Resolution,
			&i.OutputKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, input_key, status, error_message, created_at, updated_at FROM jobs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.InputKey,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT id, input_key, status, error_message, created_at, updated_at FROM jobs
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListJobsByStatus(ctx context.Context, status JobStatus) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.InputKey,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $2, error_message = $3
WHERE id = $1
RETURNING id, input_key, status, error_message, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       JobStatus   `json:"status"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.InputKey,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRenditionOutputKey = `-- name: UpdateRenditionOutputKey :one
UPDATE renditions
SET output_key = $2
WHERE id = $1
RETURNING id, job_id, resolution, output_key, created_at
`

type UpdateRenditionOutputKeyParams struct {
	ID        pgtype.UUID `json:"id"`
	OutputKey *string     `json:"output_key"`
}

func (q *Queries) UpdateRenditionOutputKey(ctx context.Context, arg UpdateRenditionOutputKeyParams) (Rendition, error) {
	row := q.db.QueryRow(ctx, updateRenditionOutputKey, arg.ID, arg.OutputKey)
	var i Rendition
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Resolution,
		&i.OutputKey,
		&i.CreatedAt,
	)
	return i, err
}
